id: P706D0DFB
initial_creation_type: input
source_metadata:
  title: Nyala Pema Dündul Series
  language: zh
  description: 'Texts by and about the great siddha of Nyarong, Nyala Pema Dündul
    (nyag bla padma bdud ''dul, 1816–1872):'
  volume:
    42350ef267c347ea8da56ce3ffea0b68:
      title: Advice Revealing How Our Faults Become Clear
      parent: Advice
    cbfc828733da4aa9ad8b86bfd115abe3:
      title: Advice on Abandoning the Eight Worldly Concerns
      parent: Advice
    53e4089ac9c4425bbb511f12232e1dfc:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    d4fba99f87db4a8096b7d7e555df7dc7:
      title: Signs that the Common Preliminary Practices Have Penetrated the Mind
      parent: Advice
    f35e2cd16bc6458c9371dfdcc548bfd1:
      title: Song of Advice for Giving Up Meat Eating
      parent: Advice
    0daec07851344147a2bd8d636c314169:
      title: The Heaven of Solitude
      parent: Advice
    f7c4b2d20840453fa33a599de9d81a88:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Confession
    e53808ef3cf24afcac2b67d3bde3825f:
      title: Dharmakāya Transference
      parent: Phowa
    96c07152ef7c4cc0a60826885b5fdb71:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
created_at: '2022-03-01T01:03:40.617499'
last_modified_at: '2022-03-01T01:03:40.617501'
